import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/features/query/QueryProvider";
import { Toaster } from "react-hot-toast";
import Header from "@/features/components/Header";
import Categories from "@/features/components/Categories";
import Footer from "@/features/components/Footer";
import SubFooter from "@/features/components/SubFooter";
import MainLayout from "@/features/layouts/MainLayout";
import { FavouriteProvider } from "@/features/context/FavouriteContext";
import { FilterProvider } from "@/features/context/FilterContext";
import { FilterToggleProvider } from "@/features/context/FilterToggleContext";
import { CartContextProvider } from "@/features/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <FavouriteProvider>
            <FilterProvider>
              <FilterToggleProvider>
                <CartContextProvider>
                  <MainLayout>{children}</MainLayout>
                </CartContextProvider>
              </FilterToggleProvider>
            </FilterProvider>
          </FavouriteProvider>

          <Toaster position="bottom-center" />
        </QueryProvider>
      </body>
    </html>
  );
}
